### PR TITLE
Add `iron-media-change` event when mq changes

### PR DESCRIPTION
**Pull request by ebidel**
I'm porting an app and am missing this from core-mq: https://github.com/Polymer/core-media-query/blob/master/core-media-query.html#L83

R: @rictic @notwaldorf

### CODE REVIEW

**Comment by ebidel** [comment]
cc @cdata b/c he likes pull requests :stuck_out_tongue_closed_eyes:

**Comment by blasten** [comment]
@ebidel `on-query-matches-changed` didn't work?

**Comment by ebidel** [comment]
Hmm. Didn't think to use that. This brings up a good question for properties that notify. Do we want developers to use them for their own purposes? If so, it's easy to forget that notifying properties fire an event (I did!).

**Comment by blasten** [comment]
That's a valid point. This element doesn't seem to have a test or demo for `on-query-matches-changed`...

**Comment by ebidel** [comment]
I can add a test for this change.

**Comment by bicknellr** [comment]
It seems more idiomatic (to me, at least) to use the built-in `x-changed` events. There's documentation for these events in [the page about data binding](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html), but [the events page](https://www.polymer-project.org/1.0/docs/devguide/events.html) doesn't mention them at all, even though it's a pretty reasonable place to expect to hear about this and especially given that it explains other globally available events (i.e. gestures). A demo for an `x-changed` event (in addition to binding to property `x`) is probably overkill given you could then argue that a similar demo should exist for every notifying property in every element.

**Comment by bicknellr** [comment]
Filed: https://github.com/Polymer/polymer/issues/3078

**Comment by ebidel** [comment]
I'm fine with ditching this PR. Theres no reason to fire two events for the same reason.

I guess this becomes a question for the team on how we document `*-changed` events. Maybe it's a matter of adding them explicitly under the events section of API docs? That should be easy since `notify: true` is the give away.

Again, I knew notifying properties fire the event, but it's not something you remember when looking at element docs. I also suspect

cc. @garlicnation @arthurevans @cdata for their thoughts.

Filed: https://github.com/PolymerElements/iron-doc-viewer/issues/67

**Comment by bicknellr** [comment]
I agree - change events are the only way out of the binding system but aren't very well advertised.

**Comment by arthurevans** [comment]
Yes, please! It's not the first time it's been brought up.

https://github.com/PolymerElements/iron-component-page/issues/32#issuecomment-111642388

**Pull request closed without merging**
